format_code_in_doc_comments = true
wrap_comments = true
format_strings = true
imports_granularity = "Crate"
reorder_imports = true
reorder_modules = true
use_small_heuristics = "Max"
use_field_init_shorthand = true
merge_derives = false
chain_width = 60
max_width = 80
